# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train: C:\\Users\\Senuki\\Vehicle_Detection_Data\\dataset\\images\\train\\
val: C:\\Users\\Senuki\\Vehicle_Detection_Data\\dataset\\images\\val\\
# number of classes
nc: 3

# class names
names: ['car', 'bus', 'truck']